const initialState = {
  tempBookmark: {
    isEdit: false,
    isLoading: false,
    data: null,
    error: null,
  },

  guestBookmarks: {
    bookmarkId: 3,
    category: { 0: '카테고리를 추가하세요' },
    bookmarks: [
      {
        category: '카테고리를 추가하세요',
        categoryId: 0,
        id: 0,
        text: '새로운 북마크를 추가하세요 1',
        url: 'https://www.google.com/',
        importance: 1,
        color: '#214bc8',
        visitCounts: 1,
        position: 1,
      },
      {
        category: '카테고리를 추가하세요',
        categoryId: 0,
        id: 1,
        text: '새로운 북마크를 추가하세요 2',
        url: 'https://www.google.com/',
        importance: 1,
        color: '#214bc8',
        visitCounts: 1,
        position: 2,
      },
      {
        category: '카테고리를 추가하세요',
        categoryId: 0,
        id: 2,
        text: '새로운 북마크를 추가하세요 3',
        url: 'https://www.google.com/',
        importance: 1,
        color: '#214bc8',
        visitCounts: 1,
        position: 3,
      },
    ],
    reducedbookmarks: [
      {
        id: 0,
        title: '카테고리를 추가하세요',
        bookmarks: [
          {
            category: '카테고리를 추가하세요',
            categoryId: 0,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요',
            categoryId: 0,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요',
            categoryId: 0,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 1,
        title: '카테고리를 추가하세요1',
        bookmarks: [
          {
            category: '카테고리를 추가하세요1',
            categoryId: 1,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요1',
            categoryId: 1,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요1',
            categoryId: 1,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 2,
        title: '카테고리를 추가하세요2',
        bookmarks: [
          {
            category: '카테고리를 추가하세요2',
            categoryId: 2,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요2',
            categoryId: 2,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요2',
            categoryId: 2,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 3,
        title: '카테고리를 추가하세요3',
        bookmarks: [
          {
            category: '카테고리를 추가하세요1',
            categoryId: 3,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요3',
            categoryId: 3,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요3',
            categoryId: 3,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 4,
        title: '카테고리를 추가하세요4',
        bookmarks: [
          {
            category: '카테고리를 추가하세요4',
            categoryId: 4,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요4',
            categoryId: 4,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요4',
            categoryId: 4,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 5,
        title: '카테고리를 추가하세요5',
        bookmarks: [
          {
            category: '카테고리를 추가하세요1',
            categoryId: 5,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요5',
            categoryId: 5,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요5',
            categoryId: 5,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 6,
        title: '카테고리를 추가하세요6',
        bookmarks: [
          {
            category: '카테고리를 추가하세요1',
            categoryId: 6,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요6',
            categoryId: 6,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요6',
            categoryId: 6,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 7,
        title: '카테고리를 추가하세요7',
        bookmarks: [
          {
            category: '카테고리를 추가하세요7',
            categoryId: 7,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요7',
            categoryId: 7,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요7',
            categoryId: 7,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 8,
        title: '카테고리를 추가하세요8',
        bookmarks: [
          {
            category: '카테고리를 추가하세요1',
            categoryId: 8,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요8',
            categoryId: 8,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요8',
            categoryId: 8,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
      {
        id: 9,
        title: '카테고리를 추가하세요9',
        bookmarks: [
          {
            category: '카테고리를 추가하세요1',
            categoryId: 9,
            id: 0,
            text: '새로운 북마크를 추가하세요 1',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요9',
            categoryId: 9,
            id: 1,
            text: '새로운 북마크를 추가하세요 2',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
          {
            category: '카테고리를 추가하세요9',
            categoryId: 9,
            id: 2,
            text: '새로운 북마크를 추가하세요 3',
            url: 'https://www.google.com/',
            importance: 1,
            color: '#214bc8',
            visitCounts: 1,
          },
        ],
      },
    ],
  },
  unreadBookmarks: null,
  userBookmarks: {
    reducedbookmarks: [],
    category: [],
    bookmarks: [],
    isLoading: false,
    error: null,
  },
};
export default initialState;
