export const userInfoLists = [
  {
    id: 1,
    username: "김지우",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 2,
    username: "김시윤",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 3,
    username: "박유빈",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 4,
    username: "이석준",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 5,
    username: "정리벽 개발자2",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 6,
    username: "정리벽 개발자2",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 7,
    username: "정리벽 개발자2",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 8,
    username: "정리벽 개발자2",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 9,
    username: "정리벽 개발자2",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
  {
    id: 10,
    username: "정리벽 개발자2",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    github: "github.com/re-collect",
  },
];
