export const userInfoLists = [
  {
    id: 1,
    username: "Jiwoo52",
    recollects: 52,
    followers: 178,
    follwing: 140,
    company: "Team Collector",
    gitRepo: "https://github.com/re-collect",
  },
  {
    id: 2,
    username: "Siyoon3",
    recollects: 30,
    followers: 200,
    follwing: 300,
    company: "Team Collector",
    gitRepo: "https://github.com/re-collect",
  },
  {
    id: 3,
    username: "0_Yubin",
    recollects: 16,
    followers: 460,
    follwing: 300,
    company: "Team Collector",
    gitRepo: "https://github.com/re-collect",
  },
  {
    id: 4,
    username: "SeokJun",
    recollects: 30,
    followers: 300,
    follwing: 33,
    company: "Team Collector",
    gitRepo: "https://github.com/re-collect",
  },
];
